set tdesc filename gdb/workaround.xml

set remote hardware-breakpoint-limit 6
set remote hardware-watchpoint-limit 4

target remote localhost:3333

monitor halt
monitor poll

monitor flash probe 0

monitor reset halt

monitor flash erase_sector 0 0 7
monitor flash write_image build/beeclickarm.elf

#monitor flash write_image erase build/beeclickarm.elf

monitor reset halt
monitor soft_reset_halt
